name: "Automated tests"

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit tests (Jest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: yarn --frozen-lockfile
      - run: yarn test
